services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile-app
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8080 -t /var/www/html/public
    ports:
      - ${APP_PORT:-8080}:8080
    environment:
      MYSQL_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      PHP_IDE_CONFIG: serverName=localhost
    volumes:
      - .:/var/www/html
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - db
    networks:
      - promo

  db:
    image: mysql:8
    ports:
      - ${DATABASE_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_DATABASE_TEST: '${MYSQL_DATABASE}_test'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ./exchange:/var/lib/mysql-files/exchange
    networks:
      - promo

volumes:
  db-data:
    driver: local

networks:
  promo:
    driver: bridge
