FROM php:8.2-cli-alpine

RUN docker-php-ext-install pdo pdo_mysql
RUN apk add --no-cache --virtual .build-deps $PHPIZE_DEPS linux-headers \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && apk del -f .build-deps

COPY --from=composer /usr/bin/composer /usr/local/bin/composer
